service: dio-file-diory

frameworkVersion: '3'

custom:
  s3:
    bucket: ${env:BUCKET_NAME}

provider:
  name: aws
  region: eu-north-1
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: '*'

functions:
  generateDiory:
    handler: dist/handler.generateDiory
    environment:
      BUCKET_NAME: ${self:custom.s3.bucket}
    events:
      - s3:
          bucket: ${self:custom.s3.bucket}
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: UploadTemp
